version: '3.8'

services:
  web:
    image: php:7.4-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: biblioteca_db
      DB_USER: biblioteca_user
      DB_PASSWORD: user_pass
    command: bash -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql && apache2-foreground"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes: db_data
    environment:
      POSTGRES_DB: biblioteca_db
      POSTGRES_USER: biblioteca_user
      POSTGRES_PASSWORD: user_pass

volumes:
  db_data:

  